# numpy

In [1]:
import numpy as np

In [2]:
p=np.array([10,20,30,40])

In [3]:
print(p)

[10 20 30 40]


In [4]:
type(p)

numpy.ndarray

In [5]:
p.ndim           #shows the dimension of array

1

In [6]:
p.size           #shows the number of elements in array

4

In [7]:
p.shape          #shows the number of element in each dimension

(4,)

In [8]:
p.dtype          #shows the data type

dtype('int32')

In [9]:
q=np.array([[1,2,3,4],[5,6,7,8]])
print(q)

[[1 2 3 4]
 [5 6 7 8]]


In [10]:
q.ndim           #shows the dimension of array

2

In [11]:
q.size            #shows the number of elements in array

8

In [12]:
q.shape           #shows the number of element in each dimension (row,column)

(2, 4)

In [13]:
q.dtype

dtype('int32')

In [14]:
r=np.array([[1,1,1],[1,1,1],[1,1,1]])
r

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [15]:
r.ndim 

2

In [16]:
r.shape

(3, 3)

In [17]:
t=np.ones(5)            #used to get a new array of given shape and type, filled with ones. (row,column)
t

array([1., 1., 1., 1., 1.])

In [18]:
t.dtype

dtype('float64')

In [19]:
s=np.ones((3,4))
s

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
s.ndim

2

In [21]:
s.dtype

dtype('float64')

In [22]:
s1=np.ones((3,4),dtype=int)
s1

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [23]:
r1=np.zeros((3,4),dtype=int)
r1

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [24]:
r2=np.zeros((3,4),dtype=bool)
r2

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [25]:
r2=np.ones((3,4),dtype=bool)
r2

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [36]:
s3=np.empty((4,3))            #used to create a new array of given shape and type, without initializing entries
s3

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [27]:
a=np.arange(1,13)           #used to create array based on numerical values (from, to-1, interval)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [28]:
a1=np.arange(1,20,3)
a1

array([ 1,  4,  7, 10, 13, 16, 19])

In [29]:
a2=np.linspace(1,10,4)                #equally distributes the difference
a2

array([ 1.,  4.,  7., 10.])

In [30]:
a3=a.reshape(2,6)              #it is used to change the shape of an array without changing its data. (no. of array,row,column)
a3

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [31]:
a4=a.reshape(2,3,2)
a4

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [32]:
a4.ravel()             #used to change a multi-dimensional array into a contiguous flattened array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [33]:
a5=np.arange(1,13).reshape(2,6)
a5

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [34]:
a5.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [10]:
d = {1:'Pyhton', 2:[1, 2, 3]}

{1: 'Pyhton', 2: [1, 2, 3], 'one': 1}